swagger: "2.0"
info:
  description: "This contains availables API endpoints for transaction"
  version: "1.0.0"
  title: "Argent Bank API documentation"
host: "localhost:3001"
basePath: "/api/v1/user/profile"
schemes:
- "http"
security:
 - Bearer: []
paths:
  /transaction/findByAccount:
    get:
      tags:
      - 'Transaction'
      summary: "Finds Transaction by account"
      description: "All transactions regrouped by account of one specific period can be provied"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Attach Bearer JWT token"
        required: true
        type: "string"
      - name: "Account"
        in: "query"
        description: "Account name that need to be considered for filter"
        required: true
        type: "string"
      - name: "Start_Date"
        in: "query"
        description: "Start date"
        required: false
        type: "string"
        format: date
      - name: "End_Date"
        in: "query"
        description: "End date"
        required: false
        type: "string"
        format: date
      responses:
        "200":
          description: "successful operation"
          schema:
           $ref: "#/definitions/findByAccountResponse"
        "401":
          $ref: '#/responses/UnauthorizedError'
        "404":
          description: "Transaction not found"
  /transaction/{transactionId}:
    get:
      tags: 
      - "Transaction"
      summary: "Get detail information of a transaction from the store"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Attach Bearer JWT token"
        required: true
        type: "string"
      - name: "transactionId"
        in: "path"
        description: "ID of pet that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
           $ref: "#/definitions/findByIdResponse"
        "404":
          description: "Transaction not found"
        "401":
          $ref: '#/responses/UnauthorizedError'
    put:
      tags:
      - 'Transaction'
      summary: "Updates a transaction in the store"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Attach Bearer JWT token"
        required: true
        type: "string"
      - name: "transactionId"
        in: "path"
        description: "ID of pet that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Updated name of the pet"
        required: true
        schema:
         $ref: "#/definitions/TransactionUpdate"
      responses:
        "200":
          description: "Update successfully"
          schema:
           $ref: "#/definitions/findByIdResponse"
        "404":
          description: "Transaction not found"
        "401":
          $ref: '#/responses/UnauthorizedError'
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: >-
      Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".
definitions:
  TransactionDetail:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      Date:
        type: "string"
        format: date
      Amount:
        type: "number"
      Description:
        type: "string"
      Type:
        type: "string"
      Category:
        type: "string"
      Notes:
        type: "string"
      Balance:
        type: "number"
  TransactionMainInfo:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      Date:
        type: "string"
        format: date
      Amount:
        type: "number"
      Description:
        type: "string"
      Balance:
        type: "number" 
  TransactionUpdate:
    type: "object"
    properties:
      Category:
        type: "string"
      Notes:
        type: "string"
  findByAccountResponse:
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      body:
        type: "array"
        items:
         $ref: "#/definitions/TransactionMainInfo"
  findByIdResponse:
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      body:
         $ref: "#/definitions/TransactionDetail"
  updateResponse:
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      body:
         $ref: "#/definitions/TransactionDetail"    
responses:
 UnauthorizedError:
  description: API key is missing or invalid
  headers:
   WWW_Authenticate:
    type: "string"
